### ISSUE TITLE
v2版本解析接口失效

### ISSUE THREAD

**Issue by BruceFeIix** [5ime/video_spider#101]
接口解析结果返回201，断点结果如下图
![image](https://github.com/5ime/video_spider/assets/22093810/f6c6c7a1-ea49-4869-a4c7-85edc317b2c5)

**Comment by wj2008** [comment]
啥时候好了说一声

**Comment by 5ime** [comment]
https://github.com/5ime/video_spider/issues/102#issuecomment-1689299254
