### ISSUE TITLE
抖音接口失效了吗?

### ISSUE THREAD

**Issue by JuanFaC** [5ime/video_spider#102]
抖音接口失效了吗?

**Comment by 5ime** [comment]
貌似重新更换一下 Cookie 里面 ttwid 即可(至少现在可以

**Comment by duiaic** [comment]
> 貌似重新更换一下 Cookie 里面 ttwid 即可(至少现在可以

我用pc打开网页版，登录后提取了cookie里的ttwid  但是还是不行。难道提取方式不对吗？

**Comment by 5ime** [comment]
> > 貌似重新更换一下 Cookie 里面 ttwid 即可(至少现在可以
> 
> 我用pc打开网页版，登录后提取了cookie里的ttwid 但是还是不行。难道提取方式不对吗？

步骤没问题，可以尝试登录后提取，我 urlencode 解码之后 ttwid 的长度为 121

**Comment by duiaic** [comment]
> > > 貌似重新更换一下 Cookie 里面 ttwid 即可(至少现在可以
> > 
> > 
> > 我用pc打开网页版，登录后提取了cookie里的ttwid 但是还是不行。难道提取方式不对吗？
> 
> 步骤没问题，可以尝试登录后提取，我 urlencode 解码之后 ttwid 的长度为 121

大佬你还是直接更新一下源码吧。我解码后也是121就是不行。

**Comment by go522000** [comment]
下午好，我这边也遇到这个问题，解析后返回空。希望有哪位大侠能够提供一下方法，非常感谢。

**Comment by go522000** [comment]
临时解决了，但不知道什么原理。
就是登录PC端，然后把Cookie里面全部内容都替换掉原旧程序中的Cookie。
（这里不单单替换 ttwid 和 odin_tt , 而是将PC端获取到的整个Cookie里面全部都放进去。）

**Comment by duiaic** [comment]
> 临时解决了，但不知道什么原理。 就是登录PC端，然后把Cookie里面全部内容都替换掉原旧程序中的Cookie。 （这里不单单替换 ttwid 和 odin_tt , 而是将PC端获取到的整个Cookie里面全部都放进去。）

兄弟麻烦发一下你的cookie行不？我搞不定，不知道哪里出错。

**Comment by wj2008** [comment]
> 
ttwid不是下面这个库里自动生成的么？
https://github.com/5ime/Tiktok_Signature

**Comment by go522000** [comment]
我不知道是什么原理，在 https://www.douyin.com ，直接把整个Cookie替换上去，即可以运行。
![cookie](https://github.com/5ime/video_spider/assets/1244397/5fe15085-2ebf-4314-9f49-a42c41b657ae)

**Comment by xyabc120** [comment]
大佬们，更新一下解决的源码吧~

**Comment by juanyi-me** [comment]
> 我不知道是什么原理，在 https://www.douyin.com 登录后，搜索 odin_tt 相关内容，找到直接把整个Cookie替换上去，即可以正确获得无水印视频。 整个 cookie 中就包含了 ttwid 和 odin_tt 等一堆信息，个人猜这些与登录凭证有关，需要用自己的帐号登录后去获取。
> 
> ![cookie](https://user-images.githubusercontent.com/1244397/263618912-5fe15085-2ebf-4314-9f49-a42c41b657ae.png)

非常感谢，解决了我的问题
