### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by liuqiaomin** [5ime/video_spider#107]
可以讲讲 抖音的 获取原理吗

**Comment by 327078466** [comment]
java 需要最新代码联系我

**Comment by qingdouyun** [comment]
> java 需要最新代码联系我

如何联系？给个微信

**Comment by Juan0129** [comment]
> 可以讲讲 抖音的 获取原理吗

大概是先访问你的视频链接获取请求头里面的视频ID，然后用这个ID去拼接抖音某个专门获取视频内容的链接再进行访问一遍，就可以拿到相关的视频内容了

**Comment by 5ime** [comment]
> 可以讲讲 抖音的 获取原理吗

大部分视频平台可以参考该篇文章 https://5ime.cn/duanshipin.html
