### ISSUE TITLE
https://tiktok.iculture.cc/X-Bogus 超时，有替代品吗

### ISSUE THREAD

**Issue by 2424004764** [5ime/video_spider#108]
请求https://tiktok.iculture.cc/X-Bogu获取x-bogu超时了

![image](https://github.com/5ime/video_spider/assets/24261680/451075ce-c5fa-4578-beb4-d68b02462c8c)

有替代品吗

**Comment by 5ime** [comment]
https://github.com/5ime/video_spider?tab=readme-ov-file#faq

**Comment by Color-l** [comment]
我自己搭建的，直接post请求http://45.159.51.97/即可
<img width="827" alt="屏幕截图 2024-04-07 104841" src="https://github.com/5ime/video_spider/assets/55428198/ad1a53b5-4926-42b6-8fa4-d423809fae02">
