### ISSUE TITLE
麻烦您能写个去除tiktok和fackbook的吗

### ISSUE THREAD

**Issue by lpwyz** [5ime/video_spider#12]

**Comment by 5ime** [comment]
没思路

**Comment by lpwyz** [comment]
大佬，能否加下您QQ，或者微信，有偿咨询一下呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "5ime/video_spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [5ime/video_spider] 麻烦您能写个去除tiktok和fackbook的吗 (#12)





 
没思路

**Comment by lpwyz** [comment]
> 没思路

大佬，我刚刚用了您写的部署了一下，然后我发现，比如抖音的能解析成功，但是解析成功出来的视频地址和图片都访问不到呀

**Comment by 5ime** [comment]
访问403吗？抖音好像对请求来源进行了验证，referer设置为空试试

**Comment by lpwyz** [comment]
> 访问403吗？抖音好像对请求来源进行了验证，referer设置为空试试

直接访问不了，快手，抖音之类的，都是这样。
![image](https://user-images.githubusercontent.com/49158471/116512902-574f3b00-a8fb-11eb-9eeb-9267d29fd654.png)
比如这个，能解析，这是解析出来的视频地址：http://v26.douyinvod.com/1b316acbe6b412144e7207eafbff8712/608a66b6/video/tos/cn/tos-cn-ve-15/e9672fdcc9484d298efa409b797f9a77/?a=1128&amp;br=683&amp;bt=683&amp;btag=4&amp;cd=0%7C0%7C0&amp;ch=0&amp;cr=0&amp;cs=0&amp;cv=1&amp;dr=0&amp;ds=3&amp;er=&amp;l=202104291456280102120382181017DF53&amp;lr=&amp;mime_type=video_mp4&amp;net=0&amp;pl=0&amp;qs=0&amp;rc=ajk4NnVmOXFmNTMzNGkzM0ApZWU1Ozk3Njs3Nzg2NDg5NmcpaGRqbGRoaGRmZjZmZDBrMC8xYC0tZC0vc3MyMjFgMjNiYF42XzQyMzRjOmNwb2wrbStqdDo%3D&amp;vl=&amp;vr=

**Comment by 5ime** [comment]
复制链接 然后粘贴到地址栏访问 可以正常访问 看样子应该是对referer进行了限制
在网页`head`标签中中添加如下代码
```
<meta name="referrer" content="same-origin">
<meta name="referrer" content="no-referrer">
```
![image](https://user-images.githubusercontent.com/31686695/116513071-9da49a00-a8fb-11eb-88e0-a461e83d5c30.png)

**Comment by lpwyz** [comment]
> 复制链接 然后粘贴到地址栏访问 可以正常访问 看样子应该是对referer进行了限制
> 在网页`head`标签中中添加如下代码
> 
> ```
> <meta name="referrer" content="same-origin">
> <meta name="referrer" content="no-referrer">
> ```
> 
> ![image](https://user-images.githubusercontent.com/31686695/116513071-9da49a00-a8fb-11eb-88e0-a461e83d5c30.png)

呜呜呜，那我代码里面应该整么操作呀，刚学php没多久，呜呜呜。

**Comment by 5ime** [comment]
在提供的 demo/demo.html 中已经添加

**Comment by lpwyz** [comment]
> 在提供的 demo/demo.html 中已经添加

还是不行啊，呜呜呜，大佬，方便加一下您QQ吗，我是想部署到服务器上面，然后做接口

**Comment by lpwyz** [comment]
> 在提供的 demo/demo.html 中已经添加

因为我是想，解析成功，然后在app里面可以查看，下载的。求大佬给个思路呀，呜呜呜

**Comment by 5ime** [comment]
没写过app 没思路

**Comment by lpwyz** [comment]
> 没写过app 没思路

但是不对呀，，，我看别人之前问您的 issue里面  ，有是在小程序里面使用的，这个直接解析的链接，应该也是不能直接在微信小程序里面查看，并且下载的呀，，，小程序里面如何解决这个问题的呀。。。

**Comment by 5ime** [comment]
😥 小程序我也没写过呀

**Comment by lpwyz** [comment]
> 😥 小程序我也没写过呀

0.0 乌龙事件，我的天，我刚刚反应过来，我公司网屏蔽了，，视频。。。所以看不了。。。我用我手机发现可以看到了。。。
对了我看您的地址，我发现您的那个测试地址是支持B站的，但是我发现这个github的上面没有解析B站的视频的代码。。

**Comment by 5ime** [comment]
B站由于水印无法去除(只能下载视频)，与本项目相悖，所以本项目没添加B站

**Comment by lpwyz** [comment]
> B站由于水印无法去除(只能下载视频)，与本项目相悖，所以本项目没添加B站



> B站由于水印无法去除(只能下载视频)，与本项目相悖，所以本项目没添加B站
你的意思是，B站，根本就没有 无水印的视频吗0.0 所以获取不到0.0 。  
大佬西瓜视频cookie我整么获取啊
![image](https://user-images.githubusercontent.com/49158471/116519060-98e3e400-a903-11eb-8c42-af26928dcad1.png)
我发现现在的代码 解析不了西瓜视频，是不是需要cookie

**Comment by 5ime** [comment]
B站应该是没无水印视频
西瓜的话 打开网页版西瓜视频 f12 找到cookies复制进来即可（以哔哩哔哩为例）
![image](https://user-images.githubusercontent.com/31686695/116519524-245d7500-a904-11eb-9b7b-90c3879e4bcb.png)

**Comment by lpwyz** [comment]
> B站应该是没无水印视频
> 西瓜的话 打开网页版西瓜视频 f12 找到cookies复制进来即可（以哔哩哔哩为例）
> ![image](https://user-images.githubusercontent.com/31686695/116519524-245d7500-a904-11eb-9b7b-90c3879e4bcb.png)

我的没有呀，，
![image](https://user-images.githubusercontent.com/49158471/116520257-14926080-a905-11eb-8642-a415bdd40a4b.png)
问一下，那是不是我这个cookies过期了 每次需要手动更新啊。。。。

**Comment by 5ime** [comment]
```
按下F12，打开开发者工具，
选择"Console(控制台)"选项卡，输入document.cookie，回车就可以查看当前网站的Cookie了。
```

需要手动更新

**Comment by lpwyz** [comment]
> ```
> 按下F12，打开开发者工具，
> 选择"Console(控制台)"选项卡，输入document.cookie，回车就可以查看当前网站的Cookie了。
> ```
> 
> 需要手动更新

大佬，您好，我发现，抖音火山版解析不了啊，这是地址：https://share.huoshan.com/hotsoon/s/iUsOsvLOSh8/ 都提示解析失败

**Comment by lpwyz** [comment]
> ```
> 按下F12，打开开发者工具，
> 选择"Console(控制台)"选项卡，输入document.cookie，回车就可以查看当前网站的Cookie了。
> ```
> 
> 需要手动更新

全民K歌的好像也失效了。 地址：https://kg3.qq.com/node/user/9a5160d4da/song/play-K3nEtaG1Ph?s=9kjuxj9LIwPYR9Ua&shareuid=609f9d862328368e30&topsource=a0_pn201001006_z11_u220365154_l0_t1619686244__&chain_share_id=FqzkD3FLCpGKaiwbqOpBssRDGwLjbAiRQMGIAXx4ZRs

**Comment by lpwyz** [comment]
> ```
> 按下F12，打开开发者工具，
> 选择"Console(控制台)"选项卡，输入document.cookie，回车就可以查看当前网站的Cookie了。
> ```
> 
> 需要手动更新

呜呜呜，大佬有时间麻烦看看呀， 全民小视频和抖音火山版的那个。

**Comment by 5ime** [comment]
等有时间再修

**Comment by lbbboy** [comment]
能否来个 xposed 框架。

**Comment by 5ime** [comment]
> 能否来个 xposed 框架。

想法不错 但是我不会
