### ISSUE TITLE
大佬麻烦有时间想想那个facebook的呀，呜呜呜

### ISSUE THREAD

**Issue by lpwyz** [5ime/video_spider#13]
油管facebook呜呜呜

**Comment by 5ime** [comment]
油管有思路但是php不好实现，fb的话好像得申请开发者

**Comment by lpwyz** [comment]
> 油管有思路但是php不好实现，fb的话好像得申请开发者

我们都相信您，一定可以实现的，您可以去申请一下，试试看呀，呜呜呜

**Comment by mmat001** [comment]
tikiok可以吗

**Comment by 5ime** [comment]
> tikiok可以吗

不可以

**Comment by lpwyz** [comment]
> > tikiok可以吗
> 
> 不可以

呜呜呜呜，有空您搞个油管的呀，呜呜呜
