### ISSUE TITLE
同一个链接，有时候解析失败

### ISSUE THREAD

**Issue by EdisonCC** [5ime/video_spider#18]
大佬，同一个链接，有时候解析会出现201失败，这种需要怎么解决？
多刷新几次就成功，不知道是不是个例

http://xcx.flqdd.cn/index.php?url=https://v.douyin.com/ekoMabe/

![image](https://user-images.githubusercontent.com/24759541/122524234-7d1ad580-d04a-11eb-8435-6e94d65c174a.png)

**Comment by 5ime** [comment]
最近发现了这个问题，但是没找到原因，只知道请求的时候抖音那边返回了null

**Comment by EdisonCC** [comment]
通过这种方式 去获取的无水印链接 然后解析 是正常的，但是php文件这个就有时报错
https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=

**Comment by 5ime** [comment]
暂时不清楚问题产生的原因

**Comment by EdisonCC** [comment]
我发现抖音现在的链接变了，短链访问之后，变成这样了https://www.douyin.com/video/6976230499706539275?previous_page=app_code_link

**Comment by 5ime** [comment]
> 我发现抖音现在的链接变了，短链访问之后，变成这样了https://www.douyin.com/video/6976230499706539275?previous_page=app_code_link

因为抖音今天上线了 抖音网页版
