### ISSUE TITLE
大佬有计划增加小红书吗

### ISSUE THREAD

**Issue by EdisonCC** [5ime/video_spider#20]
小红书无水印图片下载
https://www.52pojie.cn/thread-1457463-1-1.html
(出处: 吾爱破解论坛)

**Comment by 5ime** [comment]
有视频和图集链接吗

**Comment by 5ime** [comment]
看了一下能写，但是需要cookies...不知道cookies过期时间

**Comment by EdisonCC** [comment]
视频
http://xhslink.com/Su9i0c

图集
http://xhslink.com/kTuo0c

**Comment by yzh52521** [comment]
这是我写的
使用 GuzzleHttp 和   QueryList 连个类
`
public function xiaohongshu($url)
    {
        preg_match(
            "/http[s]?:\/\/(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+/",
            $url,
            $deal_url
        );
        $client   = new Client();
        $base_url = get_headers($deal_url[0], true)['Location'];
        $response = $client->get(
            $base_url,
            [
                'headers' => [
                    "cookie"     => "xhsTrackerId=fc8afcea-2646-4b2b-cb0f-879cbb3d468b;extra_exp_ids=gif_exp1,ques_exp1; xhsuid=YXyNVadnMDjotQoI;timestamp2=20210627d596dbb636b45c829f6fdaaa; timestamp2.sig=CILEipun6jTBkGKsyZPvVi4vOjZrkgNB1GO5MpNVjSk; xhsTracker=url=noteDetail&xhsshare=CopyLink",
                    "User-Agent" => "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"
                ],
            ]
        );
        $html     = $response->getBody()->getContents();
        preg_match('/<script[\s]type=\"application\/ld\+json\">([^<]+)<\/script>/', $html, $content);
        $json        = trim(str_replace('\n', '', $content[1]));
        $json        = json_decode($json, 1, 512, JSON_THROW_ON_ERROR);
        $ql          = QueryList::html($html);
        $link        = $ql->find('video');
        $url         = $link->attr('src');
        $poster      = ':' . $link->attr('poster');
        $description = $ql->find(".content .as-p")->html();
        if ($url) {
            return [
                'code' => 200,
                'msg'  => '解析成功',
                'data' => [
                    'description' => $json['description'],
                    'title'       => $description,
                    'cover'       => $poster,
                    'url'         => $url,
                    'time'        => $json['uploadDate'],
                    'author'      => $json['author'],
                ]
            ];
        }
    }

(new VideoSpider())->xiaohongshu('70 痞幼发布了一篇小红书笔记，快来看吧！ 😆 gEghKjpz3OYlO1N 😆 http://xhslink.com/wjoC7c，复制本条信息，打开【小红书】App查看精彩内容！');
`

**Comment by 5ime** [comment]
过几天开个新仓库，会和其他平台图集整合一下

**Comment by EdisonCC** [comment]
小红书的视频去水印是同样的逻辑吗？可以加上小红书的视频去水印么

**Comment by 5ime** [comment]
> 小红书的视频去水印是同样的逻辑吗？可以加上小红书的视频去水印么

不是 图集下午就上传github
