### ISSUE TITLE
建议增加bilibili解析

### ISSUE THREAD

**Issue by babygits** [5ime/video_spider#26]
建议增加bilibili解析

**Comment by 5ime** [comment]
哔哩哔哩我用python写了一个 https://github.com/5ime/bilidown
为什么这个项目不加？
1. 哔哩哔哩需要用户**登录后**的cookies，需要定时更新
2. 哔哩哔哩下载视频需要添加**referer**，PHP无法实现此功能，没有referer会导致用户点击下载链接后显示**403**

**Comment by 5ime** [comment]
3. 哔哩哔哩是硬水印，也就是水印去不掉

**Comment by babygits** [comment]
https://docs.tenapi.cn/bilivideo.html
这个可以，虽然有水印，但还可以解析，别家的解析也可以做到mp4解析了

**Comment by 5ime** [comment]
> https://docs.tenapi.cn/bilivideo.html
> 这个可以，虽然有水印，但还可以解析，别家的解析也可以做到mp4解析了

你看看能下载吗

**Comment by babygits** [comment]
有的时候不会报错，可以看下这个https://bilibili.iiilab.com/
具体的原理就不清楚了

**Comment by 5ime** [comment]
> 有的时候不会报错，可以看下这个https://bilibili.iiilab.com/
> 具体的原理就不清楚了

你不知道我也不知道呀
