### ISSUE TITLE
全民视频 失效

### ISSUE THREAD

**Issue by yzh52521** [5ime/video_spider#27]
```

//全民小视频
    public function quanmin($url)
    {
        $client = new Client();
        $html   = $client->get(
            $url,
            [
                'headers' => [
                    'User-Agent'                => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36',
                    'upgrade-insecure-requests' => '1'
                ]
            ]
        )->getBody()->getContents();
        preg_match('/<meta property=\"og:title\" content=\"(.*?)\">/', $html, $title);
        preg_match('/<meta property=\"og:image\" content=\"(.*?)\">/', $html, $cover);
        preg_match('/<meta property=\"og:videosrc\" content=\"(.*?)\">/', $html, $video);
        preg_match('/<div class=\"author-main\"><p class=\"name\">(.*?)<\/p>/', $html, $author);
        return [
            'code' => 200,
            'msg'  => '解析成功',
            'data' => [
                "title"  => $title[1],
                "cover"  => $cover[1],
                "url"    => $video[1],
                'author' => $author[1]
            ]
        ];
    }
```

**Comment by 5ime** [comment]
全民没发现问题

**Comment by yzh52521** [comment]
> 全民没发现问题

获取不到有用的数据了

**Comment by 5ime** [comment]
> > 全民没发现问题
> 
> 获取不到有用的数据了

我这一切正常，title为空是因为没用标题
~~~
{
  "code": 200,
  "msg": "解析成功",
  "data": {
    "author": "桃子姐姐美食教程",
    "avatar": "https://himg.bdimg.com/sys/portrait/item/wise.1.6a779351.TC2p7H8LzfAo5iBJ8WaIkw.jpg?time=10197",
    "title": "",
    "cover": "https://mvideopic.bdstatic.com/mvideo/ddfdcbdfcc615ce7cd51f9a01eb4e49d?for=bg@s_0,w_800,h_1000",
    "url": "https://vd3.bdstatic.com/mda-mg886ek595xqvxs7/540p/h264_cae/1625809622626317034/mda-mg886ek595xqvxs7.mp4?pd=-1&pt=1&cr=0&vt=0&cd=0&did=cfcd208495d565ef66e7dff9f98764da&logid=1364324694&vid=5465101505779190867&auth_key=1625813564-0-0-206f9db877a772dc623840379425824c&bcevod_channel=searchbox_feed"
  }
}
~~~

**Comment by yzh52521** [comment]
> > > 全民没发现问题
> > 
> > 
> > 获取不到有用的数据了
> 
> 我这一切正常，title为空是因为没用标题
> 
> ```
> {
>   "code": 200,
>   "msg": "解析成功",
>   "data": {
>     "author": "桃子姐姐美食教程",
>     "avatar": "https://himg.bdimg.com/sys/portrait/item/wise.1.6a779351.TC2p7H8LzfAo5iBJ8WaIkw.jpg?time=10197",
>     "title": "",
>     "cover": "https://mvideopic.bdstatic.com/mvideo/ddfdcbdfcc615ce7cd51f9a01eb4e49d?for=bg@s_0,w_800,h_1000",
>     "url": "https://vd3.bdstatic.com/mda-mg886ek595xqvxs7/540p/h264_cae/1625809622626317034/mda-mg886ek595xqvxs7.mp4?pd=-1&pt=1&cr=0&vt=0&cd=0&did=cfcd208495d565ef66e7dff9f98764da&logid=1364324694&vid=5465101505779190867&auth_key=1625813564-0-0-206f9db877a772dc623840379425824c&bcevod_channel=searchbox_feed"
>   }
> }
> ```

我知道了，你传的id
我传url 就不行了
我加了两句获取ID
$vid = explode('v/', $url);
        $id  = explode('?', $vid[1])[0];

**Comment by 5ime** [comment]
> > > > 全民没发现问题
> > > 
> > > 
> > > 获取不到有用的数据了
> > 
> > 
> > 我这一切正常，title为空是因为没用标题
> > ```
> > {
> >   "code": 200,
> >   "msg": "解析成功",
> >   "data": {
> >     "author": "桃子姐姐美食教程",
> >     "avatar": "https://himg.bdimg.com/sys/portrait/item/wise.1.6a779351.TC2p7H8LzfAo5iBJ8WaIkw.jpg?time=10197",
> >     "title": "",
> >     "cover": "https://mvideopic.bdstatic.com/mvideo/ddfdcbdfcc615ce7cd51f9a01eb4e49d?for=bg@s_0,w_800,h_1000",
> >     "url": "https://vd3.bdstatic.com/mda-mg886ek595xqvxs7/540p/h264_cae/1625809622626317034/mda-mg886ek595xqvxs7.mp4?pd=-1&pt=1&cr=0&vt=0&cd=0&did=cfcd208495d565ef66e7dff9f98764da&logid=1364324694&vid=5465101505779190867&auth_key=1625813564-0-0-206f9db877a772dc623840379425824c&bcevod_channel=searchbox_feed"
> >   }
> > }
> > ```
> > 
> > ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)复制到剪切板
> 
> 我知道了，你传的id
> 我传url 就不行了
> 我加了两句获取ID
> $vid = explode('v/', $url);
> $id = explode('?', $vid[1])[0];

我就是传的url https://quanmin.hao222.com/sv2?source=share-h5&pd=qm_share_mvideo&vid=5465101505779190867&autoplay=1

**Comment by yzh52521** [comment]
> https://quanmin.hao222.com/sv2?source=share-h5&pd=qm_share_mvideo&vid=5465101505779190867&autoplay=1

你传 https://quanmin.baidu.com/v/4507611522646901410?source=share-1024102t-0&tab=share&pd=1024102t&autoplay=1 这个试试

**Comment by 5ime** [comment]
> > https://quanmin.hao222.com/sv2?source=share-h5&pd=qm_share_mvideo&vid=5465101505779190867&autoplay=1
> 
> 你传 https://quanmin.baidu.com/v/4507611522646901410?source=share-1024102t-0&tab=share&pd=1024102t&autoplay=1 这个试试

ok，我适配一下这个链接格式
