### ISSUE TITLE
演示的DEMO.HTML 有问题 输入链接后-解析-提示解析成功-但是不输出任何内容啊，首页对接测试数据又是有的

### ISSUE THREAD

**Issue by 1274003856** [5ime/video_spider#3]
比如我的
http://yadd.aote.xyz/?url=https://h5.pipix.com/s/hukXsy/
测试就是内容全部有的啊。
但是在
http://yadd.aote.xyz/demo/
输入  https://h5.pipix.com/s/hukXsy/ 解析后
只提示解析成功
并不返回任何数据啊。希望修复一下
推荐你看看这个 JSON数据提取源码哈
https://mkblog.cn/1106/

**Comment by 1274003856** [comment]
请问一下 是需要什么PHP版本和安装什么PHP扩展吗

**Comment by 5ime** [comment]
已修复 另外此页面只供测试，此项目本意是方便用户对接小程序
