### ISSUE TITLE
西瓜视频解析到的视频没声音

### ISSUE THREAD

**Issue by eclanp** [5ime/video_spider#30]
西瓜视频解析到的视频没声音，求老哥再修复一下

**Comment by 5ime** [comment]
修不了，全网都这样，有声音的视频有水印，所以说我返回了无声视频和音乐，自己合成一下吧。

**Comment by 5ime** [comment]
PHP没办法合并音视频，如果是Python很简单就能实现

**Comment by eclanp** [comment]
好像不是他们自己合并的，我找了一个微信小程序试了一下，他们解析出来的无水印，有声音。看URL应该是官方的，而不是他自己合并的：
http://v3-default.ixigua.com/4977b36da3f6ac10d436da208df16dc1/60e8833c/video/tos/cn/tos-cn-ve-4/5582e8bf034246c5870656fd6e75cbf3/?a=2011&br=1912&bt=1912&cd=0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=202107100010240102120862032823D3B1&lr=unwatermarked&mime_type=video_mp4&net=0&pl=0&qs=0&rc=ajpwbzg6ZjU8NjMzNDczM0ApNjU6PDw5NTwzN2g0aDY2Zmc0cmRwcjRvaWdgLS1kLTBzcy0zXzIuMy9eNS5hNjNeYDQ6Yw%3D%3D&vl=&vr=

**Comment by 5ime** [comment]
啊这 😥 等有时间看看

**Comment by CB1213** [comment]
西瓜视频确实没有声音，对比一下解析出来的链接：
有：v9-default.ixigua.com
无：v9-xg-web-s.ixigua.com
应该还有其他解析方式，或者是base64解析前有什么改动
