### ISSUE TITLE
快手正则貌似有问题 解决方法贴下方 另外求快手音频m4a写法

### ISSUE THREAD

**Issue by xiaoh2018** [5ime/video_spider#35]
快手的开源php正则需要修改下
preg_match(‘/srcNoMark":"(.*?)"}/‘, $text, $video_url);
需要删掉}
音频m4a能不能写个正则 我搞了半天不太对

不去掉提取出来的不是纯地址
提取出来是这样的
“url”: “https://txmov2.a.yximgs.com/upic/2021/04/26/17/BMjAyMTA0MjYxNzQ1MDJfMTE3NzMyMTc4NF80ODQ4OTk1ODYyMF8xXzM=_b_B4c389db6327921fb6037aa228c25d805.mp4?clientCacheKey=3xv8y6t3uvgpxpi_b.mp4&tt=b&di=31eaddfa&bp=13380\",\"tagShowBottom\":{\"bizId\":\"5xzefnycavcaphu\",\"bannerType\":2,\"usedCount\":\"5\",\"type\":3,\"name\":\"启大大•每晚9点户外的作品原声\",\"postScheme\":\"kwai://post?musicId=5924032058&musicType=9",
修改之后就不会有后面那一节了 你可以试试

**Comment by xiaoh2018** [comment]
快手测试视频连接：https://v.kuaishou.com/e34SGr

**Comment by 5ime** [comment]
快手视频改为：preg_match('/srcNoMark\":\"(.*?)\"/', $text, $video_url);
背景音乐的话audioUrls\":\[\{\"cdn\":\"tx2.a.yximgs.com\"\,\"url\":\"(.*?)\"} 试试，正则都差不多..自己看着改改
