### ISSUE TITLE
大佬有计划增加 小红书 快手 微博的图片无水印吗？

### ISSUE THREAD

**Issue by EdisonCC** [5ime/video_spider#4]
大佬有计划增加 小红书 快手 微博的图片无水印吗？这个非常好用，感谢！

**Comment by EdisonCC** [comment]
找到一个小红书图片去水印的，大佬有空聚合一起
https://github.com/Tammy-zting/python-xiaohongshu

**Comment by EdisonCC** [comment]
大佬，我找到个快手图集去水印的，有空可以转成PHP版

https://github.com/FioraLove/Net-Spider/tree/develop/%E5%9B%BE%E9%9B%86

**Comment by 5ime** [comment]
联系原作者转吧 我转的话感觉不太友好

**Comment by 5ime** [comment]
思路：https://5ime.cn/images-spider.html

**Comment by EdisonCC** [comment]
原作者请教过了，他说对PHP不太深入
