### ISSUE TITLE
大佬，bili能给个规则吗，我研究了好久，发现bili的地址非常难找

### ISSUE THREAD

**Issue by 15225159177** [5ime/video_spider#42]

**Comment by 5ime** [comment]
5ime/bilidown
cookies失效很快

**Comment by 5ime** [comment]
> 5ime/bilidown
> cookies失效很快

且下载需要设置Refer

**Comment by 15225159177** [comment]
> > 5ime/bildown 
> > cookie 失效循环
> 
> 且下载需要设置参考

卧槽回复这么快，好的！

**Comment by 15225159177** [comment]
大佬还有个问题，我发现微视这个接口虽然浏览器可以正常输出，但是如果用js调的话调不出来，不知道哪里的问题。我去用你的官方demo也调不出来

**Comment by 5ime** [comment]
应该是一些字符被转义了，自行对比一下吧。
