### ISSUE TITLE
抖音类似下方的长链接无法解析

### ISSUE THREAD

**Issue by njtyair** [5ime/video_spider#43]
例如：https://www.douyin.com/video/7008446980296953095
该抖音链接无法解析，拜托大神抽空看下

**Comment by 5ime** [comment]
`index.php`第`15`行
https://github.com/5ime/video_spider/blob/a3fd1ceb599043f0a2e3f6f7ace3b1b6d21406ab/index.php#L15
`src/video_spider.php`第`40`行
https://github.com/5ime/video_spider/blob/a3fd1ceb599043f0a2e3f6f7ace3b1b6d21406ab/src/video_spider.php#L40
自行加个`if`判断一下即可

**Comment by njtyair** [comment]
> `index.php`第`15`行
> https://github.com/5ime/video_spider/blob/a3fd1ceb599043f0a2e3f6f7ace3b1b6d21406ab/index.php#L15
> 
> 
> `src/video_spider.php`第`40`行
> https://github.com/5ime/video_spider/blob/a3fd1ceb599043f0a2e3f6f7ace3b1b6d21406ab/src/video_spider.php#L40
> 
> 
> 自行加个`if`判断一下即可

好的，添加如下
`if (strpos($url, 'www.douyin')) {
            $loc = explode('?',$url)[0]."?previous_page=app_code_link";
        }else{
            $loc = get_headers($url, true)['Location'][1];
        }`

**Comment by 5ime** [comment]
感觉长链接的用途不大，目前网页版和APP版分享视频链接均为短链接
