### ISSUE TITLE
希望大佬将输出的json标准化，~帖子内有json标准化教程

### ISSUE THREAD

**Issue by 1274003856** [5ime/video_spider#5]
大佬，你的这个解析输出的json不标准啊，不能被网上的免费php解析解析出来啊，希望修复

你可以看看这个帖子哦
PHP基础之解析json数据_余熙钰的博客-CSDN博客
https://blog.csdn.net/yubo_725/article/details/44980899

这就是  你的 输出
data{ }
它的是 
data[ { } ]

这个帖子的json是 
{
    "name": "zhangsan",
    "age": 21,
    "sex": "male",
    "books": [
        {
            "name": "Chinese",
            "price": "50"
        },
        {
            "name": "History",
            "price": "60"
        },
        {
            "name": "Music",
            "price": "30"
        }
    ]
}

你的是

{
    "name": "zhangsan",
    "age": 21,
    "sex": "male",
    "books": 
        {
            "name": "Chinese",
            "price": "50"
        },
        {
            "name": "History",
            "price": "60"
        },
        {
            "name": "Music",
            "price": "30"
        }
}

**Comment by 1274003856** [comment]
大佬你要是做到标准化输出json数据，
大家都好按照这个源码直接解析啦。

**Comment by 5ime** [comment]
自行修改video_spider.php return的$arr变量即可
