### ISSUE TITLE
今天dy解析不到了，是出问题了嘛

### ISSUE THREAD

**Issue by wigcw** [5ime/video_spider#50]
今天dy解析不到了，是出问题了嘛

**Comment by 5ime** [comment]
$video_url = $arr['item_list'][0]["video"]["play_addr"]["url_list"][0];

**Comment by wigcw** [comment]
谢谢

**Comment by luofengda** [comment]
> $video_url = $arr['item_list'][0]["video"]["play_addr"]["url_list"][0];

是在哪里改啊，

> 谢谢
你的改好了没

**Comment by 5ime** [comment]
> 是在哪里改啊，
> 
> >

https://github.com/5ime/video_spider/blob/a3fd1ceb599043f0a2e3f6f7ace3b1b6d21406ab/src/video_spider.php#L53
