### ISSUE TITLE
抖音已经不能解析了

### ISSUE THREAD

**Issue by ludashi2020** [5ime/video_spider#7]
https://www.iesdouyin.com/share/video/6856737027619114247/?region=CN&mid=6854453604732930830&u_code=ljiie3507hk&titleType=title&utm_source=copy_link&utm_campaign=client_share&utm_medium=android&app=aweme

**Comment by 5ime** [comment]
提交issues前请先查看 [支持的链接](https://github.com/5ime/video_spider#%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F)

**Comment by EdisonCC** [comment]
是你的链接有问题，用短连接是没问题的，刚测试了一下
