### ISSUE TITLE
请问下为什么5ime解析的地址域名都是固定的

### ISSUE THREAD

**Issue by leefuwa** [5ime/video_spider#72]
请问下为什么5ime解析的地址域名都是固定的，自己解析的域名都是变动的

**Comment by 5ime** [comment]
因为cdn缓存，所以短时间内不会变

**Comment by leefuwa** [comment]
> 因为cdn缓存，所以短时间内不会变

但是我用最新的视频，你的接口解析  还是旧的域名。。。。
