### ISSUE TITLE
想请教几个问题。

### ISSUE THREAD

**Issue by jyiwbb** [5ime/video_spider#8]
1.在demo里替换的解析接口是不是搭建好的网站？（我已经替换成网站，偶尔报错。如：https://qsy.jyiwbb.ml/?url=）
2.此项目是单纯的网页解析程序嘛？搭建好以后我用自己网站接口添加参数，跳转的还是网站首页没有变化。
3.如果搭建出来的不是解析接口，请教一下，各平台的解析接口应该怎么搭建。
麻烦大佬，希望可以解答一下我的疑惑。

**Comment by 5ime** [comment]
1.是也不是 你要替换为你的接口地址
2.不是 网页只是用作演示，你可以用接口做个解析机器人.小程序..... 至于为什么没有变化 因为你理解错了 如何使用请看`3`
3.直接上传index.php和src目录即可

**Comment by EdisonCC** [comment]
大佬，请教一下，demo里的python文件，在网页里怎么调用？

**Comment by 5ime** [comment]
> 大佬，请教一下，demo里的python文件，在网页里怎么调用？

调用不了

**Comment by EdisonCC** [comment]
只能在本地运行吗

**Comment by 5ime** [comment]
> 只能在本地运行吗

对
