### ISSUE TITLE
demo 页面解析后，点击下载无法打开

### ISSUE THREAD

**Issue by EdisonCC** [5ime/video_spider#9]
demo 页面解析后，点击下载无法打开，目前只测试了抖音，测试抖音地址https://v.douyin.com/eFDVrtA/

![image](https://user-images.githubusercontent.com/24759541/112613137-b7fdda80-8e5a-11eb-9654-e5acee77da8d.png)

![image](https://user-images.githubusercontent.com/24759541/112613204-cea43180-8e5a-11eb-9849-935616cc957b.png)

**Comment by EdisonCC** [comment]
对比发现是 

下载视频 的链接比正常解析出来的链接少了点东西 http://v95-dy-a.ixigua.com/81e21c17c3dbd7da25270b304a5fb5e0/605dba9c/video/tos/cn/tos-cn-ve-15/5ba87fd21d1840499cabee54f77bfb72/?a=1128&br=1716&bt=429&btag=4&cd=0%7C0%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=2021032617422901021213614702040317&lr=&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M2pxZHU4aXNuNDMzOGkzM0ApZmQ6Ojw1OTs0NzNmZGk4aGcpaGRqbGRoaGRmczVwMTEvMmFiYC0tMy0wc3M1MjYwX2AyLWAzMWItNDEtOmNwb2wrbStqdDo%3D&vl=&vr=

正常通过php解析的链接 http://v95.douyinvod.com/c045175be3013d38e017cae1474b673b/605db96d/video/tos/cn/tos-cn-ve-15/5ba87fd21d1840499cabee54f77bfb72/?a=1128&amp;br=1716&amp;bt=429&amp;btag=4&amp;cd=0%7C0%7C0&amp;ch=0&amp;cr=0&amp;cs=0&amp;cv=1&amp;dr=0&amp;ds=3&amp;er=&amp;l=2021032617372601021203820734034C11&amp;lr=&amp;mime_type=video_mp4&amp;net=0&amp;pl=0&amp;qs=0&amp;rc=M2pxZHU4aXNuNDMzOGkzM0ApZmQ6Ojw1OTs0NzNmZGk4aGcpaGRqbGRoaGRmczVwMTEvMmFiYC0tMy0wc3M1MjYwX2AyLWAzMWItNDEtOmNwb2wrbStqdDo%3D&amp;vl=&amp;vr=

**Comment by 5ime** [comment]
有测试地址么 我这没有复现成功

**Comment by EdisonCC** [comment]
测试地址  http://xcx.flqdd.cn/demo/demo.html

**Comment by 5ime** [comment]
看了一下应该是抖音防盗链问题 可以参考一下 https://blog.youngxj.cn/587.html

**Comment by EdisonCC** [comment]
嗯，可以了，谢谢大佬！
