### ISSUE TITLE
想用这个接口做个小程序，请问download合法域名配置有什么好的解决方案吗

### ISSUE THREAD

**Issue by wlxweb** [5ime/video_spider#91]

**Comment by 5ime** [comment]
自己备案域名即可

**Comment by wlxweb** [comment]
接口域名有了，就是使用wx.downloadFIle时候，这些资源的URl都是不固定的

**Comment by 5ime** [comment]
没了解过小程序，不过我觉得可以尝试反代？

> 接口域名有了，就是使用wx.downloadFIle时候，这些资源的URl都是不固定的
